apiVersion: batch/v1 
kind: Job
metadata:
  name: workerserverjob
spec:
  selector:
    matchLabels:
      app: workerserverpod
  template:
    metadata:
      labels:
        app: workerserverpod
    spec:      
      containers:
      - name: workerserverpod
        image: index.docker.io/brianpclab/kubernetestest02:20200107023803
        imagePullPolicy: Always
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 15
        readinessProbe:
          tcpSocket:
            path: /readiness
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 15
#        ports:
#        - containerPort: 80
#        env:
#        - name: API_PATH_BASE
#          value: "/ktest02"

